Open-Source-Chandigarh/Brewtopia

client/src/App.js
client/src/components/cartitem.js
client/src/components/product.js
client/src/styles/App.css

I've moved the selecting quantity option from product to carditem page. Please check and suggest any changes if required, I would love to work upon it. @Varinder-Dhillon0  closes #5

MOVE: Range from product to cart

---

client/src/sign-up.js

This PR fixes the bug in password length while signing up and closes #13

FIX: password length bug

---

README.md

close #1
I have added a detailed README.md file please review it. Thank you

added detailed readme

---

client/src/styles/App.css

issue #9 (resolve)
I added some animation on the nav button when they are hovering and made some animation changes on the menu item on the nav. I am providing the screenshots for better understanding.
|previous|
after
the animation are applied when we are hovering on them.

fix #9 add animation on nav button

---

client/src/App.js

Added a link to a GitHub, LinkedIn, and Twitter icon.
The social icons on the footer section are working properly.
https://github.com/Open-Source-Chandigarh/Brewtopia/assets/111897568/9a8431e5-96b7-4f5b-bc12-dfbf5d9b5dfb

Fixed issue #28

---

server/controllers/user.js
server/package-lock.json
server/package.json

Added hashing of password to store in database

---

client/src/index.js

Resolved the login path issue that was causing the redirection to 'App.js' (Homepage) after successful login.
#25

login route resolved

---

client/src/styles/App.css

Fix padding around the cart and order button

fix padding around cart and order button

---

client/src/menu.js

#6 Fix Images

---

client/src/login.js
client/src/sign-up.js
client/src/styles/login.css

improve responsiveness of signup and signin

---

server/.gitignore

gitignore file added in the server directory

gitignore file added

---

client/src/index.js

If user is logged in then unassigned path will redirect to App.js
If user not logged in then it will redirect to Login.js 
#38

wildcard issue fixed

---

client/src/styles/App.css

hii @Varinder-Dhillon0, The footer is responsive for all devices now. I also added hover effects on social links. Issue #10

footer-updated. Issue #10

---

client/src/App.js
client/src/components/product.js
client/src/styles/App.css

Search Bar function implemented

#46 Search Bar

---

server/config/db.js
server/controllers/payment.js
server/controllers/user.js
server/index.js

Close #2 
I have fixed backend code please review. Thank you.

fix_backend

---

client/src/login.js
client/src/sign-up.js

Add: signup/login on enter

---

client/src/components/cart.js
client/src/components/cartitem.js

Modified cartitem.js

---

client/src/App.js
client/src/components/scrolltoTop.js
client/src/components/scrolltoTop.module.css

This PR adds the scroll to top feature and closes #22

ADD: scroll to top button

---

client/src/styles/login.css

Added To-Fro Motion On Login Page

---

client/src/login.js
client/src/sign-up.js

added toggle button for password input view for login and sighnup page
#79

toggle added

---

server/middleware/rateLimiter.js
server/package-lock.json
server/package.json
server/routes/cart.js
server/routes/orders.js
server/routes/payment.js
server/routes/user.js

API-rate-limiter added

---

client/src/components/cart.js
client/src/styles/login.css

#89 
#94
added the login.css file missing in previous pr

rupee symbol added

---

client/.env.example
client/src/App.js
client/src/styles/App.css

Issue #90 
Make searchbar responsive

fix searchbar responsiveness

---

client/src/App.js

search value trimmed

---

README.md

[Issue Add Tags to README.md is Completed.](https://github.com/Open-Source-Chandigarh/Brewtopia/issues/83)

Issue #83 => Add Tags to README.md is Completed.

---

README.md

Addressing issue #102. Updated README.md to add environment variables for locally setting up the project.

Update README.md (Issue #102)

---

client/src/sign-up.js
client/src/styles/login.css

This pull request introduces enhancements to the user registration functionality by adding a Confirm Password field, implementing a check for password and confirm password matching, and enforcing strong password criteria using regular expressions.
- **Added Confirm Password Field:** Included a new Confirm Password field in the user registration form to improve user experience and security.
- **Implemented Password Matching Check:** Ensured that the entered password and confirm password fields must match, providing users with immediate feedback during registration.
- **Enforced Strong Password Criteria:** Utilized regular expressions to enforce strong password requirements, guaranteeing that users create secure passwords.
- Tested the new Confirm Password field to ensure it functions …

feat:Added Confirm Password Field

---

client/src/App.js
client/src/components/Search.js
client/src/context/FilterContext.js
client/src/index.js
client/src/sign-up.js
client/src/styles/App.css
client/src/styles/search.css

Issue #114 
added a search page

feat: search page

---

client/src/components/FilterSidebar.js
client/src/styles/filterSidebar.css
client/src/styles/search.css

Hey @Varinder-Dhillon0  , kindly consider merging this pull request under the #116. It appears that the latest update in #121 only includes a screenshot of the UI and doesn't incorporate the current changes. Please review the changes in this pull request for the correct updates. Thanks!

filterbar redesign complete
